spring:
  application:
    name: contract-management
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/contract-management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: osci
    password: osci1!#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: contract-ocr-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest


openapi:
  service:
    url: /swagger-ui.html

llm:
  ollama:
    url: http://localhost:11434
    model: exaone3.5:2.4b

ocr:
  server:
    url: http://localhost:8884

# 업로드된 계약서 파일 저장 위치 (로컬 테스트용)
file:
  storage:
    local-path: ./uploads

# JWT 설정
jwt:
  secret: SHrj0iqVOTY8N9mXb9NZCcCJVfO+3rO4omcjUWub6vk=
  access-expiration: 3600 # 1h
  refresh-expiration: 1209600 # 2w